### ISSUE TITLE
just accounterd a error after the update to your version

### ISSUE THREAD

**Issue by s-light** [tartansandal/icc-brightness#7]
thanks for your fork!

i just updated my version and found a small subprocess call that crashed:

```
$ icc-brightness watch
profile object path '/org/freedesktop/ColorManager/profiles/icc_eae1b6500d4a49ef023ce47a0398bdb2_stefan_1000' does not exist for this device
2021-12-03 21:25:22,550 - ERROR: device-make-profile-default
Traceback (most recent call last):
  File "/usr/local/bin/icc-brightness", line 287, in main
    icc_brightness_apply()
  File "/usr/local/bin/icc-brightness", line 202, in icc_brightness_apply
    icc_brightness(brightness, max_brightness)
  File "/usr/local/bin/icc-brightness", line 188, in icc_brightness
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colormgr', 'device-make-profile-default', '/org/freedesktop/ColorManager/devices/xrandr_eDP_1_stefan_1000', '/org/freedesktop/ColorManager/profiles/icc_eae1b6500d4a49ef023ce47a0398bdb2_stefan_1000']' returned non-zero exit status 1.
```

after i did a `icc-brightness clean` it was all fine again..
so it seems a little *version-conflict*.

**Comment by tartansandal** [comment]
Hi @s-light ! Thanks for you comment and apologies for the late reply (no github notification for some reason :disappointed:)

Hmm you are probably right: a little _version-conflict_. 

I could probably make a better error message, or even catch the error and automatically rebuild the profile. I'm making a small patch to log more information about the failure and, if we see it happen again, I'll be able to craft a sensible response. :smile:

**Comment by tartansandal** [comment]
Thanks @s-light. I've added the extra traps and added some troubleshooting notes, so hopefully we'll be able to clean this up if it happens. Until then, I'll close this issue. Cheers :beer:
